### ISSUE TITLE
Problem installing packages

### ISSUE THREAD

**Issue by lmachineone** [Zibetti/Plothtests#1]
First of all, congratulations on your package it's quite unique and it's very pretty. I would like very much to use it.

To install the first library "devtools" in ubuntu 20.04 LTS rstudio i had to also run in my terminal:
```
sudo apt-get install -y libssl-dev curl libssl-dev
```
After installing these 3 packages, i properly installed "devtools" in R.
After when i try to install this library the following errors occurs:

> installing to /home/hariseldon/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-igraph/00new/igraph/libs
> ** R
> ** demo
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/home/hariseldon/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-igraph/00new/igraph/libs/igraph.so':
>   libgfortran.so.4: cannot open shared object file: No such file or directory
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/home/hariseldon/R/x86_64-pc-linux-gnu-library/3.6/igraph’
> Error: Failed to install 'Plothtests' from GitHub:
>   (converted from warning) installation of package ‘igraph’ had non-zero exit status

**Comment by Zibetti** [comment]
Hi @perinm, thanks for trying the package.
Did you tryed install the "igraph" package first? Then after that try again plothtest.
